name: build
on: 
- push

jobs:
  listimages:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.get-matrix.outputs.matrix }}
    steps:
    - uses: actions/checkout@master
    - id: get-matrix
      uses: mikefarah/yq@v4.25.1
      with:
        cmd: |
          yq e .build.artifacts skaffold.yaml | sed 's/liatrio/blairdrummond/g'

  build-two:
    uses: blairdrummond/github-workflows/.github/workflows/build-scan-push.yaml@main
    needs: [listimages]
    with:
      repository: "ghcr.io/blairdrummond/github-workflows"
      tag: latest
      build-matrix: ${{ needs.listimages.outputs.matrix }}