name: push-jenkins-ghcr

env:
  REGISTRY: ghcr.io/liatrio
  IMAGE_NAME: jenkins-ignite

on: 
- push

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v1
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./jenkins-image
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - id: gitops
        uses: liatrio/github-actions/gitty-up@master
        if: github.ref == 'refs/heads/master'
        with:
          url: https://github.com/liatrio/lead-environments.git
          username: ${{ github.actor }}
          password: ${{ secrets.GITTY_UP_TOKEN }}
          file: aws/manifest.yml
          values: liatrio_sandbox.builder_images_version=${{steps.gitextra.outputs.version}}:liatrio_sandbox.jenkins_image_version=${{steps.gitextra.outputs.version}}