name: push
on: 
- push

jobs:
  listimages:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.get-matrix.outputs.result }}
    steps:
    - uses: actions/checkout@master
    - id: get-matrix
      uses: mikefarah/yq@v4.25.1
      with:
        cmd: |
          yq e .build.artifacts skaffold.yaml | sed 's/liatrio/blairdrummond/g'

  build:
    uses: liatrio/github-workflows/.github/workflows/build-scan-push.yaml@fix-scan-workflow
    needs: [listimages]
    with:
      publish: ${{ github.ref == 'refs/heads/master' }}
      repository: ghcr.io/blairdrummond
      registry-username: ${{ github.repository_owner }}
      registry-password: ${{ secrets.GITHUB_TOKEN }}
      tag: ${{ github.ref }}
      build-matrix: ${{ needs.listimages.outputs.matrix }}

  gitty-up:
    runs-on: ubuntu-18.04
    needs: [build]
    steps:
    - uses: actions/checkout@v2
    - id: gitextra
      uses: liatrio/github-actions/git-extra@master
    - id: gitops
      uses: liatrio/github-actions/gitty-up@master
      if: false
      with:
        url: https://github.com/liatrio/lead-environments.git
        username: ${{ github.actor }}
        password: ${{ secrets.GITTY_UP_TOKEN }}
        file: aws/liatrio-sandbox/manifest.yml
        values: builder_images_version=${{steps.gitextra.outputs.version}}:jenkins_image_version=${{steps.gitextra.outputs.version}}

